version: '3.7'

services:
  nvest-server:
    build:
      context: ./nvest-server
      dockerfile: Dockerfile
      target: base
    env_file:
      - ./nvest-server/.env
    volumes:
      - ./nvest-server/src:/home/node/app/src
      - ./nvest-server/nodemon.json:/home/node/app/nodemon.json
    container_name: nvest-server
    expose:
      - '5000'
    ports:
      - '5000:5000'
      - '9229:9229'
    command: npm run dev
    networks:
      - nvest-backend
  postgres:
    image: postgres
    restart: always
    container_name: nvest-pgdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./sql:/scripts
    networks:
      - nvest-backend

networks:
  nvest-backend: null
