version: '3.4'

services:
  nvest:
    image: nvest
    build:
      context: nvest-server
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 5000:5000
